MvcProjeKampi/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValideationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryvalidator = new CategoryValidator();
            ValidationResult results = categoryvalidator.Validate(p);
            if (results.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName,item.ErrorMessage);
                }
            }
                return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryvalue = cm.GetByID(id);
            cm.CategoryDelete(categoryvalue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryvalue = cm.GetByID(id);
            return View(categoryvalue);
        }

        [HttpPost]
        public ActionResult EditCategory(Category p)
        {
            cm.CategorUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValideationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FluentValidation.Results;

namespace MvcProjeKampi.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetCategoryList()
        {
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            // cm.CategortAddBL(p);
            CategoryValidator categoryValidator = new CategoryValidator();
            FluentValidation.Results.ValidationResult results = categoryValidator.Validate(p);
            if(results.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("GetCategoryList");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }



    }
}

MvcProjeKampi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult test()
        {
            return View();
        }
    }
}

MvcProjeKampi/Controllers/IstatistikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Concrate;

namespace MvcProjeKampi.Controllers
{
    public class IstatistikController : Controller
    {
        // GET: Istatistik

        Context c = new Context();
        
        public ActionResult Index()
        {
            var categoryCount = c.Categories.Count().ToString();
            ViewBag.CategoryCount = categoryCount;

            var heading = c.Headings.Count(l => l.CategoryID == 15).ToString();
            ViewBag.Heading = heading;

            var writer = c.Writers.Where(w => w.WriterName.Contains("a") || w.WriterName.Contains("A")).Count();
            ViewBag.Writer = writer;

            var headingMax = c.Headings.Where(u => u.CategoryID == c.Headings.GroupBy(x => x.CategoryID).OrderByDescending(x => x.Count())
               .Select(x => x.Key).FirstOrDefault()).Select(x => x.Category.CategoryName).FirstOrDefault();
            ViewBag.HeadingMax = headingMax;

            var trueStatus = c.Categories.Where(c => c.CategoryStatus == true).Count();
            var falseStatus = c.Categories.Where(c => c.CategoryStatus == false).Count();

            ViewBag.Status = (trueStatus - falseStatus);


            return View();
        }
    }
}

MvcProjeKampi/Controllers/TESTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class TESTController : Controller
    {
        // GET: TEST
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult test2()
        {
            return View();
        }
    }
}

MvcProjeKampi/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Kategori Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new{ @class="form-control"})
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /> <br />
        @Html.Label("Açıklamayı Yazınız")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /> <br />
        <button class="btn btn-info">Kaydet</button>

    </div>
}

MvcProjeKampi/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Kategori Güncelleme Sayfası</h2>
@using(Html.BeginForm("EditCategory","AdminCategory",FormMethod.Post))
            {
    <div class="form-group">
        @Html.Label("Kategori ID")
        @Html.TextBoxFor(x => x.CategoryID, new {@class="form-control"})
        <br />
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
            }

MvcProjeKampi/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>KATEGORİ ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>BAŞLIKLAR</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>@item.CategoryID</th>
            <td>@item.CategoryName</td>
           
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger">SİL</a></td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryID" class="btn btn-warning">GÜNCELLE</a></td>
            <td><a href="#" class="btn btn-primary">BAŞLIKLAR</a></td>
        </tr>
    }

</table>

<a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori</a>

MvcProjeKampi/Views/Category/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h1>Yeni Kategori Ekleme Sayfası</h1>
<br />
@using(Html.BeginForm("AddCategory","Category",FormMethod.Post))
            {
               <div class="form-group">
                   @Html.Label("Kategori Adı")
                   @Html.TextBoxFor(x=>x.CategoryName)
                   @Html.ValidationMessageFor(x=>x.CategoryName)
                   <br /> <br />
                   @Html.Label("Açıklamayı Yazınız")
                   @Html.TextBoxFor(x=>x.CategoryDescription)
                   @Html.ValidationMessageFor(x=>x.CategoryDescription)
                   <br /> <br />
                   <button>Kaydet</button>

               </div>
            }

@*<form class="form-group" method="post">
    <input type="text" placeholder="Kategori Adı" name="CategoryName" class="form-control" />
    <br />
    <input type="text" placeholder="Açıklama Giriniz" name="CategoryDescription" class="form-control" />
    <br />
    <button class="btn btn-primary">Ekle</button>

</form>*@

MvcProjeKampi/Views/Category/GetCategoryList.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    Layout = null;
}


<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>AD</th>
        <th>DURUM</th>
    </tr>

    @foreach(var item in Model)
            {
                <tr>
                    <td>@item.CategoryID</td>
                    <td>@item.CategoryName</td>
                    <td>@item.CategoryStatus</td>
                </tr>
            }

</table>
<br />
<a href="/Category/AddCategory" class="btn btn-info">Yeni Kategori</a>

MvcProjeKampi/Views/Category/Index.cshtml
@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h3>Mvc Kamp Tablo Örneği - Kategori </h3>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>ADI</th>
        <th>AÇIKLAMA</th>
        <th>DURUM</th>
        <th>GÜNCELLE</th>
        
    </tr>
    <tr>
        <td>1</td>
        <td>Eğitim</td>
        <td>Açıklama Yaptık</td>
        <td>True</td>
        <td><button class="btn btn-success">Güncele</button></td>
    </tr>
    <tr>
        <td>2</td>
        <td>Spor</td>
        <td>Açıklama Yapıldı</td>
        <td>True</td>
        <td><button class="btn btn-success">Güncele</button></td>
    </tr>
    <tr>
        <td>3</td>
        <td>Kitap</td>
        <td>Açıklama Yapıldı</td>
        <td>True</td>
        <td><button class="btn btn-success">Güncele</button></td>
    </tr>
    <tr>
        <td>4</td>
        <td>Sinema</td>
        <td>Açıklama Bekleniyor</td>
        <td>True</td>
        <td><button class="btn btn-success">Güncele</button></td>
    </tr>




</table>

<button class="btn btn-info">Yeni Kategori</button>
<button class="btn btn-warning">Kategori Listesi</button>
<button class="btn btn-danger">Kategori Açıklamaları</button>

MvcProjeKampi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

<br />
<h1>MERHABA MVC PROJE KAMPI BAŞLADI </h1>

MvcProjeKampi/Views/Home/test.cshtml
@{
    ViewBag.Title = "test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>test</h2>

<br />
<p>AD:NURDAN ÖZDEMİR</p>
<p>MESLEK: YAZILIM</p>

MvcProjeKampi/Views/Istatistik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-4 mt-3 mr-6">
            <div class="card text-white bg-olive mb-3" style="width:350px;height:200px">
                <div class="card-body">
                    <h1>@ViewBag.categoryCount</h1>
                    <p class="card-text" style="font-size:28px">Toplam Kategori Sayısı</p>
                </div>
            </div>
        </div>
        <div class=" col-md-4 mt-3 mr-4">
            <div class="card text-white bg-cyan mb-3" style="width:350px;height:200px">
                <div class="card-body">
                    <h1>@ViewBag.heading</h1>
                    <p class="card-text" style="font-size:28px">"Yazılım" Kategorisine Ait Başlık Sayısı</p>
                </div>
            </div>
        </div>
        <div class="col-md-3 mt-3 mr-4">
            <div class="card text-white bg-pink mb-3" style="width:350px;height:200px">
                <div class="card-body">
                    <h1>@ViewBag.writer</h1>
                    <p class="card-text" style="font-size:28px">Adında 'A' Harfi Geçen Yazar Sayısı</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 mt-3 mr-4">
            <div class="card text-white bg-gradient-yellow mb-3" style="width:350px;height:200px">
                <div class="card-body">
                    <h1>@ViewBag.headingMax</h1>
                    <p class="card-text" style="font-size:28px">En Fazla Başlığa Sahip Kategori</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 mt-3 mr-4">
            <div class="card text-white bg-gradient-orange mb-3" style="width:350px;height:200px">
                <div class="card-body">
                    <h1>@ViewBag.Status</h1>
                    <p class="card-text" style="font-size:28px">Durumu True İle False Olanlar Arasındaki Fark</p>
                </div>
            </div>
        </div>
    </div>
</div>

MvcProjeKampi/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>AdminLTE 3 | Dashboard 3</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4 youtube/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4 youtube/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/AdminLTE-3.0.4 youtube/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/AdminLTE-3.0.4 youtube/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">N.Ö</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="/AdminCategory/Index" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Kategoriler

                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="pages/widgets.html" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Başlıklar

                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Yazarlar

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Grafikler
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/charts/chartjs.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/flot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/inline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 3</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    Hakkımızda

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    İletişim & Mesajlar

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Yazılar

                                </p>
                            </a>

                        </li>

                        <li class="nav-item">
                            <a href="pages/calendar.html" class="nav-link">
                                <i class="nav-icon fas fa-calendar-alt"></i>
                                <p>
                                    Yetkilendirmeler

                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/gallery.html" class="nav-link">
                                <i class="nav-icon far fa-image"></i>
                                <p>
                                    Galeri
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-envelope"></i>
                                <p>
                                    Hata Sayfaları
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>

                        </li>


                        <li class="nav-item has-treeview">
                            <a href="/Istatistik/Index" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    İstatistik

                                </p>
                            </a>

                        </li>


                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Siteye Git

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-apple-alt"></i>
                                <p>
                                    Çıkış Yap

                                </p>
                            </a>

                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                @RenderBody()
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4 youtube/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/AdminLTE-3.0.4 youtube/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/AdminLTE-3.0.4 youtube/dist/js/adminlte.js"></script>
    <!-- OPTIONAL SCRIPTS -->
    <script src="~/AdminLTE-3.0.4 youtube/plugins/chart.js/Chart.min.js"></script>
    <script src="~/AdminLTE-3.0.4 youtube/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4 youtube/dist/js/pages/dashboard3.js"></script>
</body>
</html>

MvcProjeKampi/Views/Shared/_Deneme.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Burası Title</title>
</head>
<body>
    <div>
        burası layout
    </div>
    <div> 
        @RenderBody()
    </div>
</body>
</html>

MvcProjeKampi/Views/TEST/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Deneme.cshtml";
}

<h2>Index</h2>

<br />
<p>selam</p>

MvcProjeKampi/Views/TEST/test2.cshtml
@{
    ViewBag.Title = "test2";
    Layout = "~/Views/Shared/_Deneme.cshtml";
}

<h2>burası 2. test sayfasıdır</h2>